name: My Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing..."

  test2:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Test 2
        run: echo "Testing 2..."

  deploy:
    runs-on: ubuntu-latest
    needs: [test, test2]
    steps:
      - name: Deploy
        run: echo "Deploying..."
